spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
#mybatis:
#  mapper-locations: classpath:com/gome/arch/dao/xml/*.xml
#  type-aliases-package: com.gome.arch.dao.bean
#
arch:
  support:
    mysql:
      standalone:
        enabled: true
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        maxActive: 100 # 最大连接数
        initialSize: 5  # 初始连接数
    mybatis:
      enabled: true
      mapperSqlXmls: classpath:com/gome/arch/dao/xml/*.xml
      mapperBeanPackages: com.gome.arch.dao.bean
      mapperInterfacePackages: com.gome.arch.dao.mapper