

feign:
  hystrix:
    enabled: false

hystrix:
  stream:
    queue:
      enabled: true
  command:
    default:
      fallback:
        enabled: true
      requestCache:
        enabled: true
      requestLog:
        enabled: true
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
        forceOpen: false
        forceClosed: true
      healthSnapshot:
        intervalInMilliseconds: 500
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  threadpool:
    default:
      coreSize: 10
      maximumSize: 100
      maxQueueSize: -1
      queueSizeRejectionThreshild: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 10


#设置整体的超时时间
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 10000
  okToRetryOnAllOperations: true
  maxAutoRetriesNextServer: 2
  maxAutoRetries: 1

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      forceRequest: true
      forceResponse: true
  sleuth:
    enabled: false
    sampler:
      probability: 1.0
  session:
    storeType: REDIS
    timeout: 3600
    redis:
      flushMode: IMMEDIATE
  #  rabbitmq:
  #    host: 10.115.3.191
  #    port: 5672
  #    username: wyl
  #    password: wyl
  redis:
    host: 10.115.4.149
    port: 6379
    database: 0
    jedis:
      pool:
        minIdle: 1
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: gome-flow-service


#单机直连其他微服务用于调试
#app-middleware-impl:
#  feign:
#    url:  10.144.37.87:8080

#eureka:
#  server:
#    enableSelfPreservation: false
#    evictionIntervalTimerInMs: 5000
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10
#    leaseExpirationDurationInSeconds: 30
#    healthCheckUrlPath: ${management.endpoints.web.basePath}/health
#    statusPageUrlPath: ${management.endpoints.web.basePath}/info
#    metadataMap:
#      cluster: MIDDLEWARE
#      management.context-path: ${management.endpoints.web.basePath}
#  client:
#    enabled: true
#    eurekaServiceUrlPollIntervalSeconds: 300
#    eurekaServerTotalConnections: 30
#    eurekaServerTotalConnectionsPerHost: 10
#    fetchRegistry: true
#    registerWithEureka: true
#    availabilityZones:
#      defaultRegion: defaultZone
#    region: defaultRegion
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://10.115.3.1:8080/eureka/,http://10.115.3.2:8080/eureka/
#####################数据库扩展配置#######################

springfox:
  documentation:
    swagger:
      v2:
        path: ${arch.support.swagger2.urlPath:/v2/api-docs}

arch:
  support:
    mysql:
      standalone:
        enabled: true
        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/gome_flow?characterEncoding=utf-8&useSSL=false
        url: jdbc:mysql://meixin-mysql-one.pre.cloud.db:5310/gome_flow?characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 123456
        username: dev_pw_archcloud
        password: 26xhviO9f5Dq
        maxActive: 100 # 最大连接数
        initialSize: 5  # 初始连接数
    mybatis:
      enabled: true
      mapperSqlXmls: classpath:com/gome/arch/dao/xml/*.xml
      mapperBeanPackages: com.gome.arch.dao.bean
      mapperInterfacePackages: com.gome.arch.dao.mapper
      pagehelper:
        enabled: true
        offsetAsPageNum: true  #默认为false，为 true 时，会将 RowBounds 中的 offset 参数当成 pageNum 使用
        rowBoundsWithCount: false #默认为false，为true时，使用 RowBounds 分页会进行 count 查询。
        pageSizeZero: false #默认为false，为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
        reasonable: false  #默认为false，为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
        supportMethodsArguments: false #默认值false，支持通过 Mapper 接口参数来传递分页参数，自动根据上面 params 配置的字段中取值
        dialect: #自定义分页逻辑需要设置这个值为分页的类
        helperDialect: mysql  #配置分页对应的数据库
        autoRuntimeDialect: false #默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
        autoDialect:
        closeConn: true #默认值为 true。当使用运行时动态数据源或没有设置 helperDialect 属性自动获取数据库类型时，会自动获取一个数据库连接， 通过该属性来设置是否关闭获取的这个连接
        params: count=countSql  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射
    jersey2:
      enabled: true
      urlMappings: /api/*
      jaxrsApplicationClass: com.gome.arch.config.RestJerseyRegister
    swagger2:  #访问地址：http:xxx:8080/swagger-ui.html
      enabled: true
      configId: gome-flow-service-swagger2-jersey2
      title:  流程服务-REST服务接口列表
      version:  1.0.0
      contact: nihui
      schemes: http,https
      basePath: /api
      resourcePackage: com.gome.arch.resource
      prettyPrint: true
      scan: true
      urlPath: /api/swagger.json








